/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.gc.CollabSphereApp.event;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class PostLikedEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3698314290053308176L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PostLikedEvent\",\"namespace\":\"com.gc.CollabSphereApp.event\",\"fields\":[{\"name\":\"id\",\"type\":\"long\",\"default\":0},{\"name\":\"postid\",\"type\":\"long\",\"default\":0},{\"name\":\"userid\",\"type\":\"long\",\"default\":0}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<PostLikedEvent> ENCODER =
      new BinaryMessageEncoder<PostLikedEvent>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<PostLikedEvent> DECODER =
      new BinaryMessageDecoder<PostLikedEvent>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<PostLikedEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<PostLikedEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<PostLikedEvent>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this PostLikedEvent to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a PostLikedEvent from a ByteBuffer. */
  public static PostLikedEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public long id;
  @Deprecated public long postid;
  @Deprecated public long userid;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public PostLikedEvent() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param postid The new value for postid
   * @param userid The new value for userid
   */
  public PostLikedEvent(java.lang.Long id, java.lang.Long postid, java.lang.Long userid) {
    this.id = id;
    this.postid = postid;
    this.userid = userid;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return postid;
    case 2: return userid;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Long)value$; break;
    case 1: postid = (java.lang.Long)value$; break;
    case 2: userid = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.Long value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'postid' field.
   * @return The value of the 'postid' field.
   */
  public java.lang.Long getPostid() {
    return postid;
  }

  /**
   * Sets the value of the 'postid' field.
   * @param value the value to set.
   */
  public void setPostid(java.lang.Long value) {
    this.postid = value;
  }

  /**
   * Gets the value of the 'userid' field.
   * @return The value of the 'userid' field.
   */
  public java.lang.Long getUserid() {
    return userid;
  }

  /**
   * Sets the value of the 'userid' field.
   * @param value the value to set.
   */
  public void setUserid(java.lang.Long value) {
    this.userid = value;
  }

  /**
   * Creates a new PostLikedEvent RecordBuilder.
   * @return A new PostLikedEvent RecordBuilder
   */
  public static com.gc.CollabSphereApp.event.PostLikedEvent.Builder newBuilder() {
    return new com.gc.CollabSphereApp.event.PostLikedEvent.Builder();
  }

  /**
   * Creates a new PostLikedEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new PostLikedEvent RecordBuilder
   */
  public static com.gc.CollabSphereApp.event.PostLikedEvent.Builder newBuilder(com.gc.CollabSphereApp.event.PostLikedEvent.Builder other) {
    return new com.gc.CollabSphereApp.event.PostLikedEvent.Builder(other);
  }

  /**
   * Creates a new PostLikedEvent RecordBuilder by copying an existing PostLikedEvent instance.
   * @param other The existing instance to copy.
   * @return A new PostLikedEvent RecordBuilder
   */
  public static com.gc.CollabSphereApp.event.PostLikedEvent.Builder newBuilder(com.gc.CollabSphereApp.event.PostLikedEvent other) {
    return new com.gc.CollabSphereApp.event.PostLikedEvent.Builder(other);
  }

  /**
   * RecordBuilder for PostLikedEvent instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PostLikedEvent>
    implements org.apache.avro.data.RecordBuilder<PostLikedEvent> {

    private long id;
    private long postid;
    private long userid;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.gc.CollabSphereApp.event.PostLikedEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.postid)) {
        this.postid = data().deepCopy(fields()[1].schema(), other.postid);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.userid)) {
        this.userid = data().deepCopy(fields()[2].schema(), other.userid);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing PostLikedEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.gc.CollabSphereApp.event.PostLikedEvent other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.postid)) {
        this.postid = data().deepCopy(fields()[1].schema(), other.postid);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.userid)) {
        this.userid = data().deepCopy(fields()[2].schema(), other.userid);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.Long getId() {
      return id;
    }

    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.gc.CollabSphereApp.event.PostLikedEvent.Builder setId(long value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.gc.CollabSphereApp.event.PostLikedEvent.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'postid' field.
      * @return The value.
      */
    public java.lang.Long getPostid() {
      return postid;
    }

    /**
      * Sets the value of the 'postid' field.
      * @param value The value of 'postid'.
      * @return This builder.
      */
    public com.gc.CollabSphereApp.event.PostLikedEvent.Builder setPostid(long value) {
      validate(fields()[1], value);
      this.postid = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'postid' field has been set.
      * @return True if the 'postid' field has been set, false otherwise.
      */
    public boolean hasPostid() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'postid' field.
      * @return This builder.
      */
    public com.gc.CollabSphereApp.event.PostLikedEvent.Builder clearPostid() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'userid' field.
      * @return The value.
      */
    public java.lang.Long getUserid() {
      return userid;
    }

    /**
      * Sets the value of the 'userid' field.
      * @param value The value of 'userid'.
      * @return This builder.
      */
    public com.gc.CollabSphereApp.event.PostLikedEvent.Builder setUserid(long value) {
      validate(fields()[2], value);
      this.userid = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'userid' field has been set.
      * @return True if the 'userid' field has been set, false otherwise.
      */
    public boolean hasUserid() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'userid' field.
      * @return This builder.
      */
    public com.gc.CollabSphereApp.event.PostLikedEvent.Builder clearUserid() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public PostLikedEvent build() {
      try {
        PostLikedEvent record = new PostLikedEvent();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Long) defaultValue(fields()[0]);
        record.postid = fieldSetFlags()[1] ? this.postid : (java.lang.Long) defaultValue(fields()[1]);
        record.userid = fieldSetFlags()[2] ? this.userid : (java.lang.Long) defaultValue(fields()[2]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<PostLikedEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<PostLikedEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<PostLikedEvent>
    READER$ = (org.apache.avro.io.DatumReader<PostLikedEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
