kafka:
  topic:
    user-created-topic: user-created-topic

spring:
  kafka:
    bootstrap-servers: localhost:9092
    admin:
      auto-create: false
      properties:
        default.api.timeout.ms: 1000
        request.timeout.ms: 1000
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: "http://localhost:8081"
        specific.avro.reader: "true"
        max.block.ms: 1000
        request.timeout.ms: 1000
        delivery.timeout.ms: 3000
