/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.gc.CollabSphereApp.event;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class SendConnectionEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -693483711923292165L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"SendConnectionEvent\",\"namespace\":\"com.gc.CollabSphereApp.event\",\"fields\":[{\"name\":\"senderId\",\"type\":\"long\",\"default\":0},{\"name\":\"receiverId\",\"type\":\"long\",\"default\":0}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<SendConnectionEvent> ENCODER =
      new BinaryMessageEncoder<SendConnectionEvent>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<SendConnectionEvent> DECODER =
      new BinaryMessageDecoder<SendConnectionEvent>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<SendConnectionEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<SendConnectionEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<SendConnectionEvent>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this SendConnectionEvent to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a SendConnectionEvent from a ByteBuffer. */
  public static SendConnectionEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public long senderId;
  @Deprecated public long receiverId;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public SendConnectionEvent() {}

  /**
   * All-args constructor.
   * @param senderId The new value for senderId
   * @param receiverId The new value for receiverId
   */
  public SendConnectionEvent(java.lang.Long senderId, java.lang.Long receiverId) {
    this.senderId = senderId;
    this.receiverId = receiverId;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return senderId;
    case 1: return receiverId;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: senderId = (java.lang.Long)value$; break;
    case 1: receiverId = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'senderId' field.
   * @return The value of the 'senderId' field.
   */
  public java.lang.Long getSenderId() {
    return senderId;
  }

  /**
   * Sets the value of the 'senderId' field.
   * @param value the value to set.
   */
  public void setSenderId(java.lang.Long value) {
    this.senderId = value;
  }

  /**
   * Gets the value of the 'receiverId' field.
   * @return The value of the 'receiverId' field.
   */
  public java.lang.Long getReceiverId() {
    return receiverId;
  }

  /**
   * Sets the value of the 'receiverId' field.
   * @param value the value to set.
   */
  public void setReceiverId(java.lang.Long value) {
    this.receiverId = value;
  }

  /**
   * Creates a new SendConnectionEvent RecordBuilder.
   * @return A new SendConnectionEvent RecordBuilder
   */
  public static com.gc.CollabSphereApp.event.SendConnectionEvent.Builder newBuilder() {
    return new com.gc.CollabSphereApp.event.SendConnectionEvent.Builder();
  }

  /**
   * Creates a new SendConnectionEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new SendConnectionEvent RecordBuilder
   */
  public static com.gc.CollabSphereApp.event.SendConnectionEvent.Builder newBuilder(com.gc.CollabSphereApp.event.SendConnectionEvent.Builder other) {
    return new com.gc.CollabSphereApp.event.SendConnectionEvent.Builder(other);
  }

  /**
   * Creates a new SendConnectionEvent RecordBuilder by copying an existing SendConnectionEvent instance.
   * @param other The existing instance to copy.
   * @return A new SendConnectionEvent RecordBuilder
   */
  public static com.gc.CollabSphereApp.event.SendConnectionEvent.Builder newBuilder(com.gc.CollabSphereApp.event.SendConnectionEvent other) {
    return new com.gc.CollabSphereApp.event.SendConnectionEvent.Builder(other);
  }

  /**
   * RecordBuilder for SendConnectionEvent instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<SendConnectionEvent>
    implements org.apache.avro.data.RecordBuilder<SendConnectionEvent> {

    private long senderId;
    private long receiverId;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.gc.CollabSphereApp.event.SendConnectionEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.senderId)) {
        this.senderId = data().deepCopy(fields()[0].schema(), other.senderId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.receiverId)) {
        this.receiverId = data().deepCopy(fields()[1].schema(), other.receiverId);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing SendConnectionEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.gc.CollabSphereApp.event.SendConnectionEvent other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.senderId)) {
        this.senderId = data().deepCopy(fields()[0].schema(), other.senderId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.receiverId)) {
        this.receiverId = data().deepCopy(fields()[1].schema(), other.receiverId);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'senderId' field.
      * @return The value.
      */
    public java.lang.Long getSenderId() {
      return senderId;
    }

    /**
      * Sets the value of the 'senderId' field.
      * @param value The value of 'senderId'.
      * @return This builder.
      */
    public com.gc.CollabSphereApp.event.SendConnectionEvent.Builder setSenderId(long value) {
      validate(fields()[0], value);
      this.senderId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'senderId' field has been set.
      * @return True if the 'senderId' field has been set, false otherwise.
      */
    public boolean hasSenderId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'senderId' field.
      * @return This builder.
      */
    public com.gc.CollabSphereApp.event.SendConnectionEvent.Builder clearSenderId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'receiverId' field.
      * @return The value.
      */
    public java.lang.Long getReceiverId() {
      return receiverId;
    }

    /**
      * Sets the value of the 'receiverId' field.
      * @param value The value of 'receiverId'.
      * @return This builder.
      */
    public com.gc.CollabSphereApp.event.SendConnectionEvent.Builder setReceiverId(long value) {
      validate(fields()[1], value);
      this.receiverId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'receiverId' field has been set.
      * @return True if the 'receiverId' field has been set, false otherwise.
      */
    public boolean hasReceiverId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'receiverId' field.
      * @return This builder.
      */
    public com.gc.CollabSphereApp.event.SendConnectionEvent.Builder clearReceiverId() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public SendConnectionEvent build() {
      try {
        SendConnectionEvent record = new SendConnectionEvent();
        record.senderId = fieldSetFlags()[0] ? this.senderId : (java.lang.Long) defaultValue(fields()[0]);
        record.receiverId = fieldSetFlags()[1] ? this.receiverId : (java.lang.Long) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<SendConnectionEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<SendConnectionEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<SendConnectionEvent>
    READER$ = (org.apache.avro.io.DatumReader<SendConnectionEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
